CREATE TABLE IF NOT EXISTS Users (
    UserID CHAR(20) PRIMARY KEY,
    Consent BOOLEAN NOT NULL DEFAULT FALSE
) WITHOUT ROWID;

CREATE TABLE IF NOT EXISTS Guilds (
    GuildID CHAR(20) PRIMARY KEY,
    Prefix CHAR(1) NOT NULL DEFAULT ','
) WITHOUT ROWID;

CREATE TABLE IF NOT EXISTS Conversations (
    ConversationID INTEGER PRIMARY KEY ASC,
    StartedAt CHAR(35) NOT NULL,
    EndedAt CHAR(35),
    GuildID CHAR(20) REFERENCES Guilds(GuildID) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS Audio (
    AudioID INTEGER PRIMARY KEY ASC,
    StartedAt CHAR(35) NOT NULL,
    EndedAt CHAR(35),
    URL VARCHAR(100),
    UserID CHAR(20) REFERENCES Users(UserID) ON UPDATE CASCADE ON DELETE SET NULL,
    ConversationID INTEGER REFERENCES Conversations(ConversationID) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS UsersConversations (
    UserID CHAR(20) REFERENCES Users(UserID) ON UPDATE CASCADE ON DELETE CASCADE,
    ConversationID INTEGER REFERENCES Conversations(ConversationID) ON UPDATE CASCADE ON DELETE CASCADE
);
